version: "3.1"

services: 
    monitoring.sample:
        container_name: sample-monitoring
        build: 
            context: .
            dockerfile: ./Dockerfile
        ports: 
            - 8088:80
            - 5000:5000
        depends_on: 
            - postgres
        networks: 
            - monitoring

    postgres:
        image: postgres:9.4
        hostname: postgres
        volumes:
            - ./init/data.sql:/docker-entrypoint-initdb.d/data.sql
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=admin
            - POSTGRES_USER=admin
            - POSTGRES_DB=customer
        networks: 
            - monitoring

    adminer:
        image: adminer:latest
        restart: always
        ports:
            - 8080:8080
        depends_on: 
            - postgres
        networks: 
            - monitoring
   
networks: 
    monitoring:
        driver: bridge
